### ISSUE TITLE
Cannot start lambda server

### ISSUE THREAD

**Issue by agrippanux** [netlify/create-react-app-lambda#7] opened 2018-10-17 14:20 UTC
Node version: 10.10 (but also doesn't work on 8.x)
OS: Ubuntu 18.04

Issue happens with either `yarn start` and `yarn start:lambda`

```bash
> yarn start:lambda                                                                                                                                                 master [98c9fc6] modified
yarn run v1.10.1
$ netlify-lambda serve src/lambda
netlify-lambda: Starting server
Lambda server is listening on 9000
Unhandled rejection Error: Cannot find module '/home/darren/code/create-react-app-lambda/lambda/hello'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.resolve (internal/modules/cjs/helpers.js:30:19)
    at Object.clearCache (/home/darren/code/create-react-app-lambda/node_modules/netlify-lambda/lib/serve.js:105:36)
    at /home/darren/code/create-react-app-lambda/node_modules/netlify-lambda/bin/cmd.js:35:16
    at Array.forEach (<anonymous>)
    at Watching.handler (/home/darren/code/create-react-app-lambda/node_modules/netlify-lambda/bin/cmd.js:34:32)
    at compiler.hooks.done.callAsync (/home/darren/code/create-react-app-lambda/node_modules/netlify-lambda/node_modules/webpack/lib/Watching.js:100:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/darren/code/create-react-app-lambda/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/darren/code/create-react-app-lambda/node_modules/tapable/lib/Hook.js:154:20)
    at Watching._done (/home/darren/code/create-react-app-lambda/node_modules/netlify-lambda/node_modules/webpack/lib/Watching.js:99:28)
    at onCompiled (/home/darren/code/create-react-app-lambda/node_modules/netlify-lambda/node_modules/webpack/lib/Watching.js:47:18)
    at hooks.afterCompile.callAsync.err (/home/darren/code/create-react-app-lambda/node_modules/netlify-lambda/node_modules/webpack/lib/Compiler.js:547:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/darren/code/create-react-app-lambda/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/darren/code/create-react-app-lambda/node_modules/tapable/lib/Hook.js:154:20)
    at compilation.seal.err (/home/darren/code/create-react-app-lambda/node_modules/netlify-lambda/node_modules/webpack/lib/Compiler.js:544:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/darren/code/create-react-app-lambda/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
```

**Comment by sw-yx** [comment] 2018-10-17 17:40
hi Darren,

i just tried this and cannot replicate. are you sure you are in the right folder? what do you get when you run `pwd`? (sorry for the really nooby question)

it says `cannot find module '/home/darren/code/create-react-app-lambda/lambda/hello'`. the correct path is `'/home/darren/code/create-react-app-lambda/src/lambda/hello'`. is there something unique about the ubuntu filesystem that you or we should adjust for? please help. (im on a mac)

**Comment by peterp** [comment] 2018-10-19 07:58
I'm able to reproduce this; the problem is that [`require.resolve`](https://github.com/netlify/netlify-lambda/blob/master/lib/serve.js#L112) throws when a module cannot be found. I'll open a PR.

**Comment by ludder** [comment] 2018-10-20 19:52
I got the same issue. Fixed it by upgrading the netlify-lambda version to 1.0.2.

**Comment by sw-yx** [comment] 2018-10-22 16:11
hmmm thanks @ludder. hey @agrippanux see if upgrading netlify-lambda solves your problem - @.peterp above also didnt seem to be replicating the same issue if i read his PR right. closing for now, feel free to reopen if still an issue (heh)

**Comment by peterp** [comment] 2018-10-22 16:35
It was exactly the same issue error message, I'll open it again once I have a reproducible repo.

**Comment by visuallization** [comment] 2018-11-24 14:06
hey guys! thanks for the tool! I appreciate your work on netlify and the surrounding development environment. 

I also had the same issue on my windows (on my mac it worked fine). Fixing the netlify-lambda version to 1.0.2. as @ludder suggested fixed it for me. There seems to be a problem with netlify-lambda 1.0.3.

**Comment by sw-yx** [comment] 2019-01-10 16:56
closing unless y'all have further issues

**Closed by sw-yx** 2019-01-10 16:56 UTC
